/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import java.lang.IllegalArgumentException
import java.lang.NullPointerException
import java.util.IllegalFormatCodePointException

val list = listOf<Int>(1,2,3,4,5,6)

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun colorPicker(color:String): Int = when(color) {
    "yellow" -> 1
    "red" -> 2
    else -> throw IllegalArgumentException("not a valid color")

}

fun main() {
colorPicker("yellow")


    fun returnString(x:List<Int>) : List<String>{
        val strings = x.map { it ->
            when (it) {
                1 -> "one"
                2 -> "two"
                else -> "other number"
            }
        }
return strings
    }
   println(returnString(list))
}

