#see that the indentation is correct!
#spring.config.import=secrets.properties
#for loading and storing secrets in a seperate file that you add to gitignore
#add spring-boot-configuration-processor
#add file to gitignore
#EnableConfigurationProperties in main class
#Create record where you enable ConfigurationProperties(xxx)
#load properties prefixed with xxx

server:
  post: 8080

spring:
  config:
    import: secrets.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: jan
    password: 9450
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
       ddl-auto: update
