#see that the indentation is correct!
server:
  post: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: jan
    password: 9450
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
       ddl-auto: update
