/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
fun inArray(array1: Array<String>, array2: Array<String>): Array<String> {
  //...
  var result: MutableList<String> = ArrayList()
  return array1.filter{e->array2.any{it.contains(e)}}.distinct().sorted().toTypedArray()
  array2.any(it.contains())

  for (s1 in array1) {
    for (s2 in array2) {
      if(s2.contains(s1)) {
       result.add(s1)
     break
      }
    }

 }

  for (x in result) {
    println(result) }

  result.sort()
  val distinct = result.toSet()
  return distinct.toTypedArray()


}


fun main() {
  inArray(arrayOf<String>("xyz", "live", "strong"), arrayOf("lively", "alive", "harp", "sharp", "armstrong"))
}
