import { NextPage } from "next";

const Login: NextPage = () => {
return (
    <div>
        <head>
              <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </head>
        <main>
            <h1>Welcome To the login page</h1>
            <p>how do you create a reactive form in react</p>
        </main>
    </div>
)
}
export default Login;